title: æ—¶å…‰ğŸ‘
favicon: 

# è‡ªåŠ¨æˆªå–æ–‡ç« çš„å‰xé•¿åº¦ä½œä¸ºæ‘˜è¦
auto_more_length: 300

menu:
  é¦–é¡µ: /
  å…³äº: /about
  å‹æƒ…é“¾æ¥: /link

links:
  - title:
      onestar
    link:
      https://onestar.newstar.net.cn/
    content:
      ONESTAR
    avatar:
      https://onestar.newstar.net.cn/images/me.jpg

valine:
  appId: WtelXWOsz6zEJvXGl3LToHOK-MdYXbMMI # leancloud application app id
  appKey: B9X5fQyROCs2pFu7yt0NeLIP # leancloud application app key

node_sass:
  outputStyle: nested
  precision: 5
  sourceComments: false